/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_novita_cobata2_OpenCVNativeClass */

#ifndef _Included_com_example_novita_cobata2_OpenCVNativeClass
#define _Included_com_example_novita_cobata2_OpenCVNativeClass
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_example_novita_cobata2_OpenCVNativeClass_getMessageFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
